server:
  port: 8191

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/tharsikan/spring-cloud-config-store
          #username:
          #passphrase:
          search-paths:
            - '*service'
