spring:
  application:
    name: rent

  datasource:
    url: jdbc:mysql://localhost:3306/rent_db?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: developer$12
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update


logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type: TRACE

server:
  port: 8866

management:
  endpoints:
    web:
      exposure:
        include: '*'

